name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Run Tests
        run: go test ./... -cover
  style:
    name: "Style"
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
    
      - name: Format codebase
        id: go-fmt-check
        run: |
          OUTPUT=$(go fmt ./...)
          if [ -n "$OUTPUT" ]; then
            echo "::error::Go fmt found unformatted files:"
            echo "$OUTPUT"
            exit 1
          fi